In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl

import xarray as xr

import thermoextrap.xtrapy as xtrapy
import thermoextrap.xtrapy.xpan_beta as xpan_beta

# Data Organization

All of the extrapolation and interpolation models in the thermoextrap package expect input data to be organized in a certain fashion. To help manage the data, there are data objects that help organize it. Even the inputs to these data object, however, must be organized appropriately. Here we will use data from our ideal gas test system to demonstrate this organization, as well as the various options for what types of data that may be provided as input.

In [3]:
#Import idealgas module
from thermoextrap.xtrapy import idealgas

#Define reference beta
beta_ref = 5.6

#And maximum order
order = 2

npart = 1000 #Number of particles (in single configuration)
nconfig = 100_000 #Number of configurations

#Generate all the data we could want
xdata, udata = idealgas.generate_data((nconfig, npart), beta_ref)

In [4]:
help(xtrapy.data)

Help on module thermoextrap.xtrapy.data in thermoextrap.xtrapy:

NAME
    thermoextrap.xtrapy.data - Routines to handle data objects

CLASSES
    abc.ABC(builtins.object)
        AbstractData
            DataCentralMomentsBase
                DataCentralMoments
                DataCentralMomentsVals
            DataValuesBase
                DataValues
                DataValuesCentral
    builtins.object
        DatasetSelector
    
    class AbstractData(abc.ABC)
     |  Helper class that provides a standard way to create an ABC using
     |  inheritance.
     |  
     |  Method resolution order:
     |      AbstractData
     |      abc.ABC
     |      builtins.object
     |  
     |  Methods defined here:
     |  
     |  __len__(self)
     |  
     |  resample(self, indices=None, nrep=None, **kwargs)
     |  
     |  ----------------------------------------------------------------------
     |  Readonly properties defined here:
     |  
     |  central
     |  
     |  order
     |

Rather than passing data directly to `__init__` methods for creating data class objects and simultaneously telling it which dimensions mean what (or expecting that specific dimensions mean a certain thing), `thermoextrap` uses xarray to label the dimensions of inputs. While this is also useful in the background, it helps to clarify what is expected of user inputs.

Currently, `xdata` is of the shape (nconfig), or the number of configurations generated with each entry being the average $x$ location for the associated configuration.

In [5]:
print(nconfig, xdata.shape)

100000 (100000,)


The dimension over which independent samples vary is the "record" dimension, with its default name in `thermoextrap` being 'rec'. So when we create an xarray `DataArray` object to house the input $x$ data, we must label that dimension 'rec'. Same goes for the input potential energy data. Note that the list provided to the argument `dims` is a list of strings naming the dimensions in the array passed to `DataArray`.

In [6]:
xdata = xr.DataArray(xdata, dims=['rec'])
udata = xr.DataArray(udata, dims=['rec'])

Now when we create a data object in `thermoextrap` to hold the data, we tell it that the "record" dimension, `rec_dim` is named 'rec', which is the default, but it could be named something different as long as you provided that name to `rec_dim`.

Note that the `xv` is the argument for the observable $x$ and `uv` is the potential energy or appropriate Hamiltonian or thermodynamic conjugate variable.

<font color="red">Difference between DataCentralMoments.from_vals and DataCentralMomentsVals.from_vals?  Seems like a resampling thing?  And can this be set up so don't need DataCentralMomentsVals?</font>

In [7]:
data = xpan_beta.DataCentralMomentsVals.from_vals(order=order, 
                                                  rec_dim='rec',
                                                  xv=xdata, uv=udata, central=True)

A couple more notes are in order about the inputs to any of the `thermoextrap` data object variants. First, you only need to provide the order you expect to extrapolate to up front if you're using the `from_vals` constructor. This is because you need to specify the order of moments that will be calculated from the raw data.

The next argument to be aware of is `central`. This is True by default and tells the data object to work with central moments for calculating derivatives in the background, which it turns out is much more numerically stable than non-central moments. You probably want `central` to be True, but know that you can change it if you wish.

A lot of data is already computed as soon as we create our data object. The original raw data is still stored in `.xv` and `.uv`, and order is `.order`, but we can already see the central moments if we look at `.values`.

In [8]:
data.values

<xarray.DataArray (xmom: 2, umom: 3)>
array([[1.00000000e+05, 1.74844851e+02, 2.82124566e+01],
       [1.74844851e-01, 2.82124566e-02, 7.36064102e-03]])
Dimensions without coordinates: xmom, umom

Understanding this internal structure will help to understand possible inputs as well. In `.values`, the data object has stored the central moments of $\langle x \rangle$ and $\langle U^i \rangle$ and cross moments $\langle x U^i \rangle$. Note that the second dimension, "umom", short for "U moments", is just `order` plus 1. That makes sense if we remember that the zeroth order derivative is the observable itself and we specify that we want to use up to `order` derivatives. So the second dimension involves setting the exponent $i$ on $U$ equal to the index of that dimension, or order of that moment. The first dimension does the same thing, but with $x$. Irregardless of the order, however, we only ever need $x$ raised to the zeroth or first power in the average.

To summarize, the first row in `.values` contains all moments of just $U$, i.e., $\langle U^0 \rangle$, $\langle U^1 \rangle$, $\langle U^2 \rangle$, etc. The second row in `.values` contains all moments of $x$ multiplied by $U$, i.e., $\langle x U^0 \rangle$, $\langle x U^1 \rangle$, etc.  But note that beyond the powers of 0 and 1 for the first row, and just 0 for the second row, all values shown are central moments, e.g., $\langle (x - \langle x \rangle)(U - \langle U \rangle)^i \rangle$ or $\langle (U - \langle U \rangle)^i \rangle$.

<font color="red">Is the average of U to the zeroth power a bug?  Doesn't seem to mess anything up because maybe never gets used... but still concerning because should just be 1, but looks like didn't get divided by the number of samples...</font>

Since this is the internal structure, you can just provide it directly (or something similar to it in terms of moments) if you prefer to do that. You'll just need to use a different constuctor method than `from_vals`.

A big caveat, though. All uncertainty estimation happens through bootstrap resampling along the 'rec' dimension of the originally provided data. So if you just pass in the central moments above, you won't be able to calculate uncertainties...

In [9]:
data_noboot = xpan_beta.DataCentralMoments.from_raw(data.values)

data_noboot.resample(nrep=3).values

ValueError: 'rec' not found in array dimensions ('xmom', 'umom')

versus...

In [10]:
data.resample(nrep=3).values

<xarray.DataArray (rep: 3, xmom: 2, umom: 3)>
array([[[1.00000000e+05, 1.74826035e+02, 2.79839210e+01],
        [1.74826035e-01, 2.79839210e-02, 7.12358505e-03]],

       [[1.00000000e+05, 1.74886323e+02, 2.82797523e+01],
        [1.74886323e-01, 2.82797523e-02, 1.04516880e-02]],

       [[1.00000000e+05, 1.74845798e+02, 2.81417099e+01],
        [1.74845798e-01, 2.81417099e-02, 7.59448993e-03]]])
Dimensions without coordinates: rep, xmom, umom

Even if you add a 'rec' dimension, bootstrapping with a single observation ('rec' dim of size 1) won't do anything...

In [11]:
data_noboot = xpan_beta.DataCentralMoments.from_raw(xr.DataArray(data.values.values[None, ...], dims=['rec', 'xmom', 'umom']))

data_noboot.resample(nrep=3).values

<xarray.DataArray (rep: 3, xmom: 2, umom: 3)>
array([[[ 1.00000000e+05,  1.74844851e+02, -3.05425095e+04],
        [ 1.74844851e-01, -3.05425095e+01,  1.06754756e+04]],

       [[ 1.00000000e+05,  1.74844851e+02, -3.05425095e+04],
        [ 1.74844851e-01, -3.05425095e+01,  1.06754756e+04]],

       [[ 1.00000000e+05,  1.74844851e+02, -3.05425095e+04],
        [ 1.74844851e-01, -3.05425095e+01,  1.06754756e+04]]])
Dimensions without coordinates: rep, xmom, umom

Resampling in this case just gives the same thing every time!

Note that whenever you call `.resample()` a new dimension is created for the output called 'rep', short for "repetitions." This is similar to the 'rec' dimension, but helps you keep track of whether you're working with original data, or a boostrapped sample.

So clearly if you like to provide raw moments, you will need to do this from blocks of your data or from repeated simulations if you want the uncertainty quantification in `thermoextrap` to work.

But if you do like to calculate your own moments (or save them periodically from simulations rather than saving all of the configurations, energies, or observable frequently), you can also make that work.

But first, we just work with blocks of data, adding an axis called 'block' that we will ask the constructor to average over by specifying the `axis` argument.

In [12]:
# Make 100 averaged observations
xx = xr.DataArray(xdata.values.reshape(100, -1), dims=['rec', 'block'])
uu = xr.DataArray(udata.values.reshape(100, -1), dims=['rec', 'block'])

In [13]:
# Create directly from values of moments - notice that this is DataCentralMoments, not DataCentralMomentsVals
# Effectively just means that the 'rec' dim will not be collapsed when using data for extrapolation, etc.
# Behaves similarly to the 'rep' dim when resampling
data_fv = xpan_beta.DataCentralMoments.from_vals(xv=xx, uv=uu, axis='block', order=order, central=True)
# So 'rec' is for each separate block average
data_fv.values

<xarray.DataArray (rec: 100, xmom: 2, umom: 3)>
array([[[ 1.00000000e+03,  1.74703826e+02,  2.68294294e+01],
        [ 1.74703826e-01,  2.68294294e-02,  6.71241371e-03]],

       [[ 1.00000000e+03,  1.75080676e+02,  3.03349208e+01],
        [ 1.75080676e-01,  3.03349208e-02,  2.66094623e-02]],

       [[ 1.00000000e+03,  1.74754354e+02,  2.48668295e+01],
        [ 1.74754354e-01,  2.48668295e-02,  9.07043168e-03]],

       [[ 1.00000000e+03,  1.74848604e+02,  3.03091785e+01],
        [ 1.74848604e-01,  3.03091785e-02,  1.89806779e-02]],

       [[ 1.00000000e+03,  1.74726521e+02,  2.89165081e+01],
        [ 1.74726521e-01,  2.89165081e-02,  4.28996831e-03]],

       [[ 1.00000000e+03,  1.75143643e+02,  2.96018837e+01],
        [ 1.75143643e-01,  2.96018837e-02, -1.23251915e-02]],

       [[ 1.00000000e+03,  1.74808502e+02,  2.88966289e+01],
        [ 1.74808502e-01,  2.88966289e-02,  2.57063988e-02]],
...
       [[ 1.00000000e+03,  1.74816774e+02,  2.82284609e+01],
        [ 1.74816774e-01,  2.82284609e-02,  6.64888329e-03]],

       [[ 1.00000000e+03,  1.74908215e+02,  2.84428338e+01],
        [ 1.74908215e-01,  2.84428338e-02,  1.18267466e-02]],

       [[ 1.00000000e+03,  1.74460937e+02,  2.88695957e+01],
        [ 1.74460937e-01,  2.88695957e-02,  1.88123799e-02]],

       [[ 1.00000000e+03,  1.74722394e+02,  2.91909998e+01],
        [ 1.74722394e-01,  2.91909998e-02,  1.42386298e-02]],

       [[ 1.00000000e+03,  1.74825205e+02,  2.70340720e+01],
        [ 1.74825205e-01,  2.70340720e-02,  6.07318177e-03]],

       [[ 1.00000000e+03,  1.74744027e+02,  2.79541070e+01],
        [ 1.74744027e-01,  2.79541070e-02,  3.13192089e-02]],

       [[ 1.00000000e+03,  1.74735209e+02,  2.74585182e+01],
        [ 1.74735209e-01,  2.74585182e-02,  3.32257756e-03]]])
Dimensions without coordinates: rec, xmom, umom

What's different here is that the 'rec' dim also appears in `.values`. That means that when this data is used in models for extrapolation or interpolation, that dimension will also be preserved. So prediction to a new $\beta$ value will result in an output matching the size of the 'rec' dimension in the same way that it would match the 'rep' dimension created through resampling.

If we resample over this data set, we see that we just take `nrep` random samples from it, putting those samples into a new dimension called 'rep'.

In [14]:
data_fv.resample(nrep=3).values

<xarray.DataArray (rep: 3, xmom: 2, umom: 3)>
array([[[1.00000000e+05, 1.74851527e+02, 2.83383204e+01],
        [1.74851527e-01, 2.83383204e-02, 6.92825748e-03]],

       [[1.00000000e+05, 1.74840605e+02, 2.81881315e+01],
        [1.74840605e-01, 2.81881315e-02, 7.24071277e-03]],

       [[1.00000000e+05, 1.74826424e+02, 2.84303241e+01],
        [1.74826424e-01, 2.84303241e-02, 7.07074444e-03]]])
Dimensions without coordinates: rep, xmom, umom

Now if we had computed the moments from the blocked data ourselves, we can also create a data object with the `from_ave_raw` constructor (below). Many other constructors exist, including from central moments if you like. If you use those, please take a look at the documentation to make sure you are specifying or using the correct dimension naming conventions, such as 'rec', 'xmom', 'umom', etc. Remember, if you are extrapolating an observable that has an explicit dependence on the extrapolation observable, you also need to specify the 'deriv' dimension that describes the observed derivatives with respect to the extrapolation variable (see the "Temperature_Extrap_Case2" notebook).

In [17]:
# Compute moments of U, i.e., averages to integer powers up to maximum order desired
mom_u = xr.DataArray(np.arange(order + 1), dims=['umom'])
uave = (uu ** mom_u).mean('block')
xuave = (xx * uu ** mom_u).mean('block')
data_fa = xpan_beta.DataCentralMoments.from_ave_raw(u=uave, xu=xuave, central=True)

In [18]:
data_fa.values

<xarray.DataArray (rec: 100, xmom: 2, umom: 3)>
array([[[ 1.00000000e+00,  1.74703826e+02,  2.68294294e+01],
        [ 1.74703826e-01,  2.68294294e-02,  6.71241371e-03]],

       [[ 1.00000000e+00,  1.75080676e+02,  3.03349208e+01],
        [ 1.75080676e-01,  3.03349208e-02,  2.66094623e-02]],

       [[ 1.00000000e+00,  1.74754354e+02,  2.48668295e+01],
        [ 1.74754354e-01,  2.48668295e-02,  9.07043167e-03]],

       [[ 1.00000000e+00,  1.74848604e+02,  3.03091785e+01],
        [ 1.74848604e-01,  3.03091785e-02,  1.89806779e-02]],

       [[ 1.00000000e+00,  1.74726521e+02,  2.89165081e+01],
        [ 1.74726521e-01,  2.89165081e-02,  4.28996834e-03]],

       [[ 1.00000000e+00,  1.75143643e+02,  2.96018837e+01],
        [ 1.75143643e-01,  2.96018837e-02, -1.23251914e-02]],

       [[ 1.00000000e+00,  1.74808502e+02,  2.88966289e+01],
        [ 1.74808502e-01,  2.88966289e-02,  2.57063988e-02]],
...
       [[ 1.00000000e+00,  1.74816774e+02,  2.82284609e+01],
        [ 1.74816774e-01,  2.82284609e-02,  6.64888329e-03]],

       [[ 1.00000000e+00,  1.74908215e+02,  2.84428338e+01],
        [ 1.74908215e-01,  2.84428338e-02,  1.18267466e-02]],

       [[ 1.00000000e+00,  1.74460937e+02,  2.88695957e+01],
        [ 1.74460937e-01,  2.88695957e-02,  1.88123799e-02]],

       [[ 1.00000000e+00,  1.74722394e+02,  2.91909998e+01],
        [ 1.74722394e-01,  2.91909998e-02,  1.42386298e-02]],

       [[ 1.00000000e+00,  1.74825205e+02,  2.70340720e+01],
        [ 1.74825205e-01,  2.70340720e-02,  6.07318176e-03]],

       [[ 1.00000000e+00,  1.74744027e+02,  2.79541070e+01],
        [ 1.74744027e-01,  2.79541070e-02,  3.13192089e-02]],

       [[ 1.00000000e+00,  1.74735209e+02,  2.74585182e+01],
        [ 1.74735209e-01,  2.74585182e-02,  3.32257755e-03]]])
Dimensions without coordinates: rec, xmom, umom

The above `.values` should be identical to those from the `from_vals` constructor.

At this point, we have seen how the same data objects that interface with extrapolation or interpolation models can be created from different inputs. Other features also exist, such as specifying weights with the argument `w` to a constructor to change the weights used during averaging.

Finally, we can also have vector-based observables, like RDFs, for example. This is easy to accomplish with any of the above constructors or types of data input. All that is required is to add another dimension to our xarray `DataArray` input. Typically, we will call this dimension 'vals', short for "values", which is the default name for this dimension when using the `DataCentralMomentVals.from_vals` constructor.

In [19]:
# Extrapolate both average x and average x**2
x_xsq_data = xr.DataArray(np.vstack([xdata.values, xdata.values**2]).T, dims=['rec', 'vals'])
data_vec = xpan_beta.DataCentralMomentsVals.from_vals(order=order, 
                                                  rec_dim='rec',
                                                  xv=x_xsq_data, uv=udata, central=True)

In [20]:
data_vec.values

<xarray.DataArray (vals: 2, xmom: 2, umom: 3)>
array([[[1.00000000e+05, 1.74844851e+02, 2.82124566e+01],
        [1.74844851e-01, 2.82124566e-02, 7.36064102e-03]],

       [[1.00000000e+05, 1.74844851e+02, 2.82124566e+01],
        [3.05989345e-02, 9.87296621e-03, 4.18546401e-03]]])
Dimensions without coordinates: vals, xmom, umom

In [21]:
data_vec.resample(nrep=3).values

<xarray.DataArray (rep: 3, vals: 2, xmom: 2, umom: 3)>
array([[[[1.00000000e+05, 1.74828772e+02, 2.82744575e+01],
         [1.74828772e-01, 2.82744575e-02, 9.53954604e-03]],

        [[1.00000000e+05, 1.74828772e+02, 2.82744575e+01],
         [3.05933739e-02, 9.89591690e-03, 4.95895307e-03]]],


       [[[1.00000000e+05, 1.74840370e+02, 2.81045484e+01],
         [1.74840370e-01, 2.81045484e-02, 8.74949485e-03]],

        [[1.00000000e+05, 1.74840370e+02, 2.81045484e+01],
         [3.05972595e-02, 9.83636878e-03, 4.69534388e-03]]],


       [[[1.00000000e+05, 1.74858937e+02, 2.82444325e+01],
         [1.74858937e-01, 2.82444325e-02, 6.27182319e-03]],

        [[1.00000000e+05, 1.74858937e+02, 2.82444325e+01],
         [3.06038921e-02, 9.88385470e-03, 3.83018549e-03]]]])
Dimensions without coordinates: rep, vals, xmom, umom

Note that we have simply added a dimension along which all the same operations happen, but independently for different data. The behavior is identical if we work instead with data from other constructors.

In [22]:
xx_xsqxsq = xr.DataArray(x_xsq_data.values.reshape(100, -1, 2), dims=['rec', 'block', 'vals'])
x_xsq_uave = (xx_xsqxsq * uu ** mom_u).mean('block')
data_fa_vec = xpan_beta.DataCentralMoments.from_ave_raw(u=uave, xu=x_xsq_uave, central=True)

In [23]:
data_fa_vec.u

<xarray.DataArray (rec: 100, vals: 2, umom: 3)>
array([[[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],
...
       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]],

       [[1., 0., 0.],
        [1., 0., 0.]]])
Dimensions without coordinates: rec, vals, umom

<font color="red">What just happened above?</font>