In [1]:
import numpy as np
import cmomy
import xarray as xr

In [26]:
x = np.random.rand(1000)
ke = np.random.rand(1000)
pe = np.random.rand(1000)

e = ke + pe

In [27]:
c_ke = cmomy.CentralMoments.from_vals((x, ke), mom=(1, 4), broadcast=True)
c_pe = cmomy.CentralMoments.from_vals((x, pe), mom=(1, 4), broadcast=True)
c_e = cmomy.CentralMoments.from_vals((x, e), mom=(1, 4), broadcast=True)

In [31]:
npart = 1000

a = cmomy.xCentralMoments.from_vals((x, e), mom=(1, 4), mom_dims=['xmom','umom'], broadcast=True)
b = cmomy.xCentralMoments.from_vals((x, e*npart), mom=(1, 4), mom_dims=['xmom','umom'], broadcast=True)

In [51]:
((a.values * npart ** a.values.umom) - b.values) / b.values

<xarray.DataArray (xmom: 2, umom: 5)>
array([[ 0.00000000e+00,  3.43716242e-16, -1.66001673e-15,
        -6.67769380e-15, -1.42935909e-15],
       [ 0.00000000e+00,  1.61145145e-15,  1.06344015e-14,
         6.80805089e-15, -1.49970254e-14]])
Dimensions without coordinates: xmom, umom

In [47]:
c = cmomy.xCentralMoments(a.values * npart ** a.values.umom, mom_ndim=a.mom_ndim)

In [50]:
(c.values - b.values) / b.values

<xarray.DataArray (xmom: 2, umom: 5)>
array([[ 0.00000000e+00,  3.43716242e-16, -1.66001673e-15,
        -6.67769380e-15, -1.42935909e-15],
       [ 0.00000000e+00,  1.61145145e-15,  1.06344015e-14,
         6.80805089e-15, -1.49970254e-14]])
Dimensions without coordinates: xmom, umom

In [36]:
a.values

<xarray.DataArray (xmom: 2, umom: 5)>
array([[1.00000000e+03, 9.92273484e-01, 1.57790262e-01, 1.29007620e-03,
        5.87139653e-02],
       [5.01459260e-01, 3.58258372e-03, 5.23833432e-04, 2.73594481e-04,
        2.70261318e-04]])
Dimensions without coordinates: xmom, umom

<CentralMoments(val_shape=(), mom=(1, 4))>
<xarray.DataArray (xmom: 2, umom: 5)>
array([[1.00000000e+03, 9.92273484e+02, 1.57790262e+05, 1.29007620e+06,
        5.87139653e+10],
       [5.01459260e-01, 3.58258372e+00, 5.23833432e+02, 2.73594481e+05,
        2.70261318e+08]])
Dimensions without coordinates: xmom, umom

In [22]:
c_e.rmom()

array([[1.        , 1.01904075, 1.20304855, 1.55947537, 2.16288003],
       [0.49994596, 0.50870492, 0.60119479, 0.78105836, 1.08683668]])

In [24]:
c_ke.rmom() + c_pe.rmom()

array([[2.        , 1.01904075, 0.68499989, 0.51571783, 0.41345004],
       [0.99989191, 0.50870492, 0.34175601, 0.25698447, 0.20569221]])

In [20]:
c_ke

<CentralMoments(val_shape=(), mom=(1, 4))>
array([[ 1.00000000e+03,  5.18125453e-01,  8.16621353e-02,
        -1.63189659e-03,  1.22475761e-02],
       [ 4.99945956e-01, -4.76624399e-04, -1.79137497e-04,
        -2.61138726e-04, -3.41012058e-05]])

In [21]:
c_pe

<CentralMoments(val_shape=(), mom=(1, 4))>
array([[ 1.00000000e+03,  5.00915294e-01,  8.39676416e-02,
        -5.46566281e-04,  1.27050933e-02],
       [ 4.99945956e-01, -2.83760006e-04,  2.50400673e-04,
        -8.58169184e-05,  5.61932068e-05]])

In [11]:
check = c_ke * 0.5 + c_pe*0.5

(array([[[1.        , 0.50108161, 0.33401187, 0.25134544, 0.20186509],
         [0.49834477, 0.24734562, 0.16425591, 0.1233063 , 0.09886354]],
 
        [[1.        , 0.50108161, 0.33401187, 0.25134544, 0.20186509],
         [0.51192235, 0.2576789 , 0.17156732, 0.12902594, 0.10360236]],
 
        [[1.        , 0.50108161, 0.33401187, 0.25134544, 0.20186509],
         [0.51176866, 0.26129325, 0.17682958, 0.13449655, 0.10892287]],
 
        [[1.        , 0.50108161, 0.33401187, 0.25134544, 0.20186509],
         [0.48864234, 0.24278554, 0.16262363, 0.12293571, 0.0989789 ]],
 
        [[1.        , 0.50108161, 0.33401187, 0.25134544, 0.20186509],
         [0.50781443, 0.25586589, 0.17064578, 0.12834757, 0.10298344]],
 
        [[1.        , 0.50108161, 0.33401187, 0.25134544, 0.20186509],
         [0.50157528, 0.25320203, 0.16883302, 0.12698589, 0.10192915]],
 
        [[1.        , 0.50108161, 0.33401187, 0.25134544, 0.20186509],
         [0.51500067, 0.25192838, 0.16528011, 0.12324006, 0

array([[[ 0.00000000e+00, -5.04477076e-01, -8.45947078e-02,
          1.10215007e-03, -5.53258685e-02],
        [ 0.00000000e+00,  2.14376088e-03,  9.23942545e-04,
          1.82026057e-03,  1.18033109e-03]],

       [[ 0.00000000e+00, -5.04477076e-01, -8.45947078e-02,
          1.10215007e-03, -5.53258685e-02],
        [ 0.00000000e+00,  5.12043241e-04,  1.22862708e-03,
         -3.82638682e-04,  1.42888648e-03]],

       [[ 0.00000000e+00, -5.04477076e-01, -8.45947078e-02,
          1.10215007e-03, -5.53258685e-02],
        [ 0.00000000e+00, -3.26562243e-03,  1.01367468e-03,
         -2.85578756e-03,  1.22771793e-03]],

       [[ 0.00000000e+00, -5.04477076e-01, -8.45947078e-02,
          1.10215007e-03, -5.53258685e-02],
        [ 0.00000000e+00,  1.31155663e-03, -3.90058394e-03,
          1.30832710e-03, -3.37675592e-03]],

       [[ 0.00000000e+00, -5.04477076e-01, -8.45947078e-02,
          1.10215007e-03, -5.53258685e-02],
        [ 0.00000000e+00, -5.18455635e-04, -2.25508173e-

In [1]:
import thermoextrap.xtrapy.xpan_beta as xpan_beta

In [3]:
import numpy as np

In [11]:
x = np.random.rand(100, 10)
u = np.random.rand(100)

In [12]:
data = xpan_beta.factory_data(u, x, 3, central=True)

In [13]:
xem = xpan_beta.factory_extrapmodel(1.0, data, minus_log=True)

In [14]:
xem.coefs.coefs(*data.xcoefs_args, order=3, norm=False, minus_log=True)

[<xarray.DataArray 'x' (val: 10)>
 array([0.73640916, 0.72389782, 0.56878801, 0.84580047, 0.62139842,
        0.69072332, 0.70485098, 0.80349812, 0.70023854, 0.70159174])
 Dimensions without coordinates: val,
 <xarray.DataArray 'x' (val: 10)>
 array([-0.01265583, -0.01364114, -0.00470076,  0.00200309,  0.00157312,
        -0.03117724,  0.00824209,  0.00214677, -0.01938677, -0.00512559])
 Dimensions without coordinates: val,
 <xarray.DataArray 'x' (val: 10)>
 array([-0.00622751, -0.00482997,  0.0014888 ,  0.00228889,  0.00225096,
         0.00890262,  0.00344893,  0.00253609,  0.00099114,  0.00246113])
 Dimensions without coordinates: val,
 <xarray.DataArray (val: 10)>
 array([ 2.29767704e-03,  6.30917970e-04,  6.11275896e-04, -1.01832760e-03,
        -1.58663961e-03,  8.53804307e-05, -1.33010180e-03,  6.93108937e-05,
         1.82126024e-03, -6.95794906e-04])
 Dimensions without coordinates: val]