In [1]:
import thermoextrap.xtrapy.xpan_beta as xpan_beta

In [3]:
import numpy as np

In [11]:
x = np.random.rand(100, 10)
u = np.random.rand(100)

In [12]:
data = xpan_beta.factory_data(u, x, 3, central=True)

In [13]:
xem = xpan_beta.factory_extrapmodel(1.0, data, minus_log=True)

In [14]:
xem.coefs.coefs(*data.xcoefs_args, order=3, norm=False, minus_log=True)

[<xarray.DataArray 'x' (val: 10)>
 array([0.73640916, 0.72389782, 0.56878801, 0.84580047, 0.62139842,
        0.69072332, 0.70485098, 0.80349812, 0.70023854, 0.70159174])
 Dimensions without coordinates: val,
 <xarray.DataArray 'x' (val: 10)>
 array([-0.01265583, -0.01364114, -0.00470076,  0.00200309,  0.00157312,
        -0.03117724,  0.00824209,  0.00214677, -0.01938677, -0.00512559])
 Dimensions without coordinates: val,
 <xarray.DataArray 'x' (val: 10)>
 array([-0.00622751, -0.00482997,  0.0014888 ,  0.00228889,  0.00225096,
         0.00890262,  0.00344893,  0.00253609,  0.00099114,  0.00246113])
 Dimensions without coordinates: val,
 <xarray.DataArray (val: 10)>
 array([ 2.29767704e-03,  6.30917970e-04,  6.11275896e-04, -1.01832760e-03,
        -1.58663961e-03,  8.53804307e-05, -1.33010180e-03,  6.93108937e-05,
         1.82126024e-03, -6.95794906e-04])
 Dimensions without coordinates: val]