In [1]:
import thermoextrap.xtrapy.xpan_beta as xpan_beta
import xarray as xr
import numpy as np

def xr_test(a, b):
    xr.testing.assert_allclose(a, b.transpose(*a.dims))

x = np.random.rand(1000, 2, 3, 4)
u = np.random.rand(1000)

# I think this actually works
data0 = xpan_beta.factory_data(u, x, 3, val=['a','b','c'], central=True)

# or just convert to xarrays
xx = xr.DataArray(x, dims=['rec','a','b','c'])
uu = xr.DataArray(u, dims=['rec'])
data1 = xpan_beta.DataValuesCentral(uv=uu, xv=xx, order=3)

xr.testing.assert_allclose(data0.dxdu,data1.dxdu)

# yet another way
data2 = xpan_beta.DataCentralMomentsVals(uv=uu, xv=xx, order=3)
xr_test(data1.dxdu, data2.dxdu)

# and yet another
data3 = xpan_beta.DataCentralMomentsVals.from_vals(uv=u, xv=x, order=3, val=['a','b','c'])
xr_test(data1.dxdu, data3.dxdu)

In [27]:
data4 = xpan_beta.factory_data(uu, xx, order=3, central=True)
xr_test(data1.dxdu, data4.dxdu)

In [38]:
data5 = xpan_beta.DataValuesCentral.from_vals(xv=xx, uv=uu, order=3)


In [70]:
# make sure we have coords

In [71]:
xxc = xx.assign_coords(
    a=lambda x: np.linspace(-1, 1, x.sizes['a']),
    b=lambda x: np.linspace(2, 5, x.sizes['b']),
    c=lambda x: np.linspace(5, 6, x.sizes['c']),
)

In [72]:
datac = xpan_beta.DataCentralMomentsVals.from_vals(xv=xxc, uv=uu, order=3)

# wrapper for stacked data

Goal convert data for gpflow analysis



In [ ]:
class StackDataGP:
    
    def __init__(self, states, xdims, ydims, 
                 alpha_name='alpha', 
                 xdims_name=None,
                 ydims_name=None,
                ):
        
        self.stats = states
        self.xdims = xdims
        self.ydims = ydims
        
        if xdims_name is None:
            xdims_name = '_xdims'
        self.xdims_name = xdims_name
        
        if ydims_name is None:
            ydims_name = '_ydims'
        self.ydims_name = ydims_name
        
    def _stack_data(self, **kws):
        
        # first resample
        self.
        
    
    

In [155]:
def stack_xr_for_gp(da, dim_n, dims_x, dims_p=None):
    """
    Given an xarray.DataArray, stack into new shape for analysis
    
    Parameters
    ----------
    
    
    Returns
    -------
    x : array, shape=(N, D)
        feature array to consider.  this will be in the order specified by dims_x
    y : array, sahpe=(N, P)
    
    
    """
    pass

In [24]:
# synthetic data
import thermoextrap.xtrapy.xpan_beta as xpan_beta
import xarray as xr
import numpy as np
import pandas as pd

betas = [0.1, 1.0]
xems = []
for beta in betas:

    rdf = xr.DataArray(np.random.rand(100, 5), dims=['rec', 'r'])
    u = xr.DataArray(np.random.rand(100), dims=['rec'])
    
    xems.append(xpan_beta.factory_extrapmodel(3, beta, u, rdf))

In [ ]:
s

In [40]:
for x in xems:
    ds = xr.Dataset({
        'mean': x.xcoefs(norm=False),
        'var': x.resample(nrep=100).xcoefs(norm=False).var('rep')
    })
    


In [25]:
coefs = (
    xr.concat((x.xcoefs(norm=False) for x in xems), dim=pd.Index(betas, name='beta'))
    .assign_coords(r=lambda x: np.linspace(0, 1, x.sizes['r']))
)

var_coefs = (
)

In [26]:
# stack to xdimensions, ydimsensions
coefs_stack = coefs.stack(_xdim=('beta','order'), _ydim=('r',))

In [32]:
X = np.array([*coefs_stack._xdim.values])
Y = coefs_stack.values

In [35]:
Y

array([[ 4.83012529e-01,  4.40315737e-01,  5.41204775e-01,
         4.97732659e-01,  5.20319080e-01],
       [-7.75613618e-04,  2.14027071e-02, -1.18215140e-02,
        -5.25870594e-03,  2.82802058e-03],
       [-2.37991943e-03, -1.98635497e-03,  1.17594343e-03,
         2.91870881e-03,  5.40365471e-04],
       [ 1.03637798e-03, -2.14102927e-03,  2.00540763e-03,
         5.10012358e-04,  8.82578056e-05],
       [ 5.06437922e-01,  4.98700042e-01,  4.93586369e-01,
         4.80760640e-01,  4.95663270e-01],
       [-5.23014008e-03,  1.12440269e-02, -1.53288765e-03,
        -3.23045787e-03,  6.00980924e-03],
       [ 1.64184961e-03, -1.75649516e-03, -4.11060025e-04,
         1.24779047e-03,  2.74793342e-04],
       [ 1.05832855e-03, -8.03850598e-04, -5.85340668e-05,
        -2.71679500e-04,  2.55671058e-04]])

In [78]:
xem = xpan_beta.factory_extrapmodel(beta=1.0, data = datac)

In [79]:
coefs = xem.xcoefs(norm=False)

In [195]:
multistack = coefs.stack(z=['a','order'], vals=['b','c'])

In [200]:
multistack

<xarray.DataArray (z: 8, vals: 12)>
array([[ 5.11764050e-01,  5.03841120e-01,  4.93675600e-01,
         5.02710211e-01,  5.11058791e-01,  4.96252234e-01,
         5.02848334e-01,  5.03835478e-01,  4.94404498e-01,
         4.94573828e-01,  5.06592000e-01,  5.00256261e-01],
       [-2.52142235e-03, -4.65908574e-03, -4.61202137e-03,
        -1.81589494e-03,  1.01906372e-04,  2.20973395e-03,
        -2.37008640e-03, -5.52389883e-03,  1.35106489e-03,
        -1.77670274e-03, -3.98951716e-03, -3.67296410e-03],
       [-1.23764950e-03, -1.14323190e-03,  5.54354152e-04,
        -7.93530931e-05,  2.99219340e-04, -7.24481533e-05,
        -1.04635550e-03,  2.60380562e-04, -6.26577038e-04,
        -4.19132965e-04,  5.46962947e-04,  1.21104138e-03],
       [ 1.21016275e-04,  4.12523998e-04,  2.87866505e-04,
         1.49481292e-04, -4.81945391e-05, -9.03013797e-05,
         3.34923481e-04,  4.20030568e-04, -1.37521133e-04,
         1.79730822e-04,  2.04470354e-04,  1.29679270e-04],
       [ 4.97708789e-01,  5.17747261e-01,  4.99833200e-01,
         4.97947795e-01,  5.10291204e-01,  4.99843122e-01,
         4.97284891e-01,  5.04159786e-01,  5.02894049e-01,
         4.88871864e-01,  5.12679361e-01,  4.99343398e-01],
       [ 3.95167456e-03, -1.14376311e-03,  3.62927712e-03,
        -6.61411223e-04,  2.80969987e-03, -1.02071901e-03,
        -2.87635134e-03, -3.13761322e-04,  1.02090072e-03,
        -1.48485718e-03,  2.03192495e-03,  1.13744272e-03],
       [ 4.54571976e-04, -1.39792083e-03, -2.54479014e-04,
         2.62581579e-04, -1.62444740e-03, -3.96727380e-04,
        -8.65031884e-06, -2.94159430e-04, -2.06865187e-04,
         4.77142095e-04,  5.45957991e-04,  7.44556061e-04],
       [-2.90851649e-04, -1.09916470e-04, -6.61068747e-04,
         4.48426447e-05,  1.45483497e-05,  8.94579653e-05,
         4.32446806e-04, -2.97142335e-04, -1.58554430e-04,
         8.77253052e-05, -7.10484457e-05,  6.21234009e-05]])
Coordinates:
  * z        (z) MultiIndex
  - a        (z) float64 -1.0 -1.0 -1.0 -1.0 1.0 1.0 1.0 1.0
  - order    (z) int64 0 1 2 3 0 1 2 3
  * vals     (vals) MultiIndex
  - b        (vals) float64 2.0 2.0 2.0 2.0 3.5 3.5 3.5 3.5 5.0 5.0 5.0 5.0
  - c        (vals) float64 5.0 5.333 5.667 6.0 5.0 ... 6.0 5.0 5.333 5.667 6.0

In [199]:
multistack.sizes['vals']

12

In [188]:
multistack.indexes['z'].names

FrozenList(['a', 'order'])

In [194]:
xr.DataArray(np.zeros_like(multistack))

<xarray.DataArray (dim_0: 8, dim_1: 12)>
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
Dimensions without coordinates: dim_0, dim_1

In [191]:
multistack.indexes['vals']

MultiIndex([(2.0,               5.0),
            (2.0, 5.333333333333333),
            (2.0, 5.666666666666667),
            (2.0,               6.0),
            (3.5,               5.0),
            (3.5, 5.333333333333333),
            (3.5, 5.666666666666667),
            (3.5,               6.0),
            (5.0,               5.0),
            (5.0, 5.333333333333333),
            (5.0, 5.666666666666667),
            (5.0,               6.0)],
           names=['b', 'c'])

In [145]:
val[*multistack.z.values]

[(-1.0, 2.0), (-1.0, 3.5), (-1.0, 5.0), (1.0, 2.0), (1.0, 3.5), (1.0, 5.0)]

In [146]:
list(multistack.z.values)

[(-1.0, 2.0), (-1.0, 3.5), (-1.0, 5.0), (1.0, 2.0), (1.0, 3.5), (1.0, 5.0)]

In [148]:
X0 = np.array(list(multistack.z.values))
X1 = np.array(list(multistack.h.values))

In [153]:
new_data = np.zeros_like(multistack.values)

In [154]:
xr.DataArray(new_data, dims=multistack.dims, coords=multistack.coords, indexes=multistack.indexes)

<xarray.DataArray (z: 6, h: 16)>
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
Coordinates:
  * z        (z) MultiIndex
  - a        (z) float64 -1.0 -1.0 -1.0 1.0 1.0 1.0
  - b        (z) float64 2.0 3.5 5.0 2.0 3.5 5.0
  * h        (h) MultiIndex
  - order    (h) int64 0 0 0 0 1 1 1 1 2 2 2 2 3 3 3 3
  - c        (h) float64 5.0 5.333 5.667 6.0 5.0 ... 6.0 5.0 5.333 5.667 6.0

In [135]:
np.array(coefs.stack(z=['a','b'], h=['order','c']).h.values)

array([(0, 5.0), (0, 5.333333333333333), (0, 5.666666666666667), (0, 6.0),
       (1, 5.0), (1, 5.333333333333333), (1, 5.666666666666667), (1, 6.0),
       (2, 5.0), (2, 5.333333333333333), (2, 5.666666666666667), (2, 6.0),
       (3, 5.0), (3, 5.333333333333333), (3, 5.666666666666667), (3, 6.0)],
      dtype=object)

In [121]:
coefs_stacked = coefs.stack(_d=('c','order'))

In [104]:
idx_xr = coefs_stacked.indexes

In [92]:
import pandas as pd

In [105]:
idx_pd = coefs.to_dataframe(name='a').index

In [120]:
np.array(list(coefs_stacked.z.values))

array([[-1.        ,  2.        ,  5.        ,  0.        ],
       [-1.        ,  2.        ,  5.        ,  1.        ],
       [-1.        ,  2.        ,  5.        ,  2.        ],
       [-1.        ,  2.        ,  5.        ,  3.        ],
       [-1.        ,  2.        ,  5.33333333,  0.        ],
       [-1.        ,  2.        ,  5.33333333,  1.        ],
       [-1.        ,  2.        ,  5.33333333,  2.        ],
       [-1.        ,  2.        ,  5.33333333,  3.        ],
       [-1.        ,  2.        ,  5.66666667,  0.        ],
       [-1.        ,  2.        ,  5.66666667,  1.        ],
       [-1.        ,  2.        ,  5.66666667,  2.        ],
       [-1.        ,  2.        ,  5.66666667,  3.        ],
       [-1.        ,  2.        ,  6.        ,  0.        ],
       [-1.        ,  2.        ,  6.        ,  1.        ],
       [-1.        ,  2.        ,  6.        ,  2.        ],
       [-1.        ,  2.        ,  6.        ,  3.        ],
       [-1.        ,  3.

In [109]:
pd.MultiIndex.from_tuples(idx_pd.values)

MultiIndex([(0, -1.0, 2.0,               5.0),
            (0, -1.0, 2.0, 5.333333333333333),
            (0, -1.0, 2.0, 5.666666666666667),
            (0, -1.0, 2.0,               6.0),
            (0, -1.0, 3.5,               5.0),
            (0, -1.0, 3.5, 5.333333333333333),
            (0, -1.0, 3.5, 5.666666666666667),
            (0, -1.0, 3.5,               6.0),
            (0, -1.0, 5.0,               5.0),
            (0, -1.0, 5.0, 5.333333333333333),
            (0, -1.0, 5.0, 5.666666666666667),
            (0, -1.0, 5.0,               6.0),
            (0,  1.0, 2.0,               5.0),
            (0,  1.0, 2.0, 5.333333333333333),
            (0,  1.0, 2.0, 5.666666666666667),
            (0,  1.0, 2.0,               6.0),
            (0,  1.0, 3.5,               5.0),
            (0,  1.0, 3.5, 5.333333333333333),
            (0,  1.0, 3.5, 5.666666666666667),
            (0,  1.0, 3.5,               6.0),
            (0,  1.0, 5.0,               5.0),
            (

In [96]:
idx

z: MultiIndex([(-1.0, 2.0,               5.0, 0),
               (-1.0, 2.0,               5.0, 1),
               (-1.0, 2.0,               5.0, 2),
               (-1.0, 2.0,               5.0, 3),
               (-1.0, 2.0, 5.333333333333333, 0),
               (-1.0, 2.0, 5.333333333333333, 1),
               (-1.0, 2.0, 5.333333333333333, 2),
               (-1.0, 2.0, 5.333333333333333, 3),
               (-1.0, 2.0, 5.666666666666667, 0),
               (-1.0, 2.0, 5.666666666666667, 1),
               (-1.0, 2.0, 5.666666666666667, 2),
               (-1.0, 2.0, 5.666666666666667, 3),
               (-1.0, 2.0,               6.0, 0),
               (-1.0, 2.0,               6.0, 1),
               (-1.0, 2.0,               6.0, 2),
               (-1.0, 2.0,               6.0, 3),
               (-1.0, 3.5,               5.0, 0),
               (-1.0, 3.5,               5.0, 1),
               (-1.0, 3.5,               5.0, 2),
               (-1.0, 3.5,               5.0, 3),


In [95]:
pd.MultiIndex.from_tuples(idx)

MultiIndex([('z',)],
           )

In [51]:
coefs.transpose('a','b','c','order').values.reshape(-1)

array([ 5.11764050e-01, -2.52142235e-03, -1.23764950e-03,  1.21016275e-04,
        5.03841120e-01, -4.65908574e-03, -1.14323190e-03,  4.12523998e-04,
        4.93675600e-01, -4.61202137e-03,  5.54354152e-04,  2.87866505e-04,
        5.02710211e-01, -1.81589494e-03, -7.93530931e-05,  1.49481292e-04,
        5.11058791e-01,  1.01906372e-04,  2.99219340e-04, -4.81945391e-05,
        4.96252234e-01,  2.20973395e-03, -7.24481533e-05, -9.03013797e-05,
        5.02848334e-01, -2.37008640e-03, -1.04635550e-03,  3.34923481e-04,
        5.03835478e-01, -5.52389883e-03,  2.60380562e-04,  4.20030568e-04,
        4.94404498e-01,  1.35106489e-03, -6.26577038e-04, -1.37521133e-04,
        4.94573828e-01, -1.77670274e-03, -4.19132965e-04,  1.79730822e-04,
        5.06592000e-01, -3.98951716e-03,  5.46962947e-04,  2.04470354e-04,
        5.00256261e-01, -3.67296410e-03,  1.21104138e-03,  1.29679270e-04,
        4.97708789e-01,  3.95167456e-03,  4.54571976e-04, -2.90851649e-04,
        5.17747261e-01, -

In [52]:
y = coefs.stack(z=('a','b','c','order'))


In [64]:
y.z.valuess

ValueError: setting an array element with a sequence.